#!/bin/bash

echo [****************************************]
echo [* building RasPi wake on Radio and RTC *]
echo [****************************************]

if [ $USER != "root" ]; then
   echo Hint: call me as root!;
   echo exiting now ...;
   exit;
fi

pushd code

i=rfm69bios
echo [... building $i]
g++ -c $i.c -lWiringPi

# compile c code
for i in rfrespond rfwait; do
    echo [... installing $i];
    g++ $i.c rfm69bios.o -o $i -lwiringPi;
    chown root:root $i;
    chmod 0755 $i;
    mv $i /usr/local/bin/;
done

# compile cpp code
for i in rfwake rfwakes; do
    echo [... installing $i];
    g++ $i.cpp rfm69bios.o -o $i -lwiringPi;
    chown root:root $i;
    chmod 0755 $i;
    mv $i /usr/local/bin/;
done

popd

# auto config gpio pin
# edit /etc/rc.local
grep -q "gpio edge 25 rising" /etc/rc.local
if [ $? -eq 1 ];
then
	echo [... modifying /etc/rc.local file];
	awk '/# rc.local/{print "gpio edge 25 rising"}1' /etc/rc.local > temp.local
	cat temp.local > /etc/rc.local
	rm temp.local
else
	echo [... already modified /etc/rc.local file];
fi

echo [*** done! ***]
