#!/bin/bash

echo [****************************************]
echo [* building RasPi wake on Radio and RTC *]
echo [****************************************]

if [ $USER != "root" ]; then
   echo Hint: call me as root!;
   echo exiting now ...;
   exit;
fi

pushd code

i=rfm69bios
echo [... building $i]
gcc -c $i.c -lWiringPi

for i in rfrespond rfwait rfwake; do
    echo [... installing $i];
    gcc $i.c rfm69bios.o -o $i -lwiringPi;
    chown root:root $i;
    chmod 0755 $i;
    cp $i /usr/local/bin/;
done

popd

echo [*** done! ***]
